#!#
# Copyright (c) 2025 Hangzhou Guanwaii Technology Co,.Ltd.
#
# This source code is licensed under the MIT License,
# which is located in the LICENSE file in the source tree's root directory.
#
# File: compose.yaml
# Author: mingcheng (mingcheng@apache.org)
# File Created: 2025-03-19 14:42:44
#
# Modified By: mingcheng (mingcheng@apache.org)
# Last Modified: 2025-03-19 15:08:59
##

services:
  hysteria:
    image: tobyxdd/hysteria
    container_name: hysteria
    restart: unless-stopped
    dns:
      - 1.1.1.1
    network_mode: "host"
    environment:
      HYSTERIA_LOG_LEVEL: "info"
    volumes:
      - ./config.yaml:/etc/hysteria.yaml
      - ./cert:/var/lib/cert
    command: ["server", "-c", "/etc/hysteria.yaml"]
    privileged: true
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    logging:
      driver: "json-file"
      options:
        max-size: "512m"
