#!#
# Copyright (c) 2025 Hangzhou Guanwaii Technology Co,.Ltd.
#
# This source code is licensed under the MIT License,
# which is located in the LICENSE file in the source tree's root directory.
#
# File: compose.client.yml
# Author: mingcheng (mingcheng@apache.org)
# File Created: 2025-03-19 14:34:41
#
# Modified By: mingcheng (mingcheng@apache.org)
# Last Modified: 2025-03-19 16:04:31
##

services:
  hysteria:
    image: tobyxdd/hysteria
    dns:
      - 1.1.1.1
    restart: unless-stopped
    environment:
      HYSTERIA_LOG_LEVEL: "warn"
    ports:
      - 1080:1080
      - 1086:1086
    volumes:
      - ./client.yaml:/etc/hysteria.yaml
      - ./cert:/var/lib/cert
    command: ["client", "-c", "/etc/hysteria.yaml"]
    privileged: true
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    logging:
      driver: "json-file"
      options:
        max-size: "512m"
