services:
  mihomo:
    image: docker.1ms.run/metacubex/mihomo
    container_name: mihomo
    environment:
      TZ: "Asia/Shanghai"
    dns:
      - 223.6.6.6
      - 223.5.5.5
    volumes:
      - ./data:/etc/mihomo
    tmpfs:
      - /tmp:size=128m,mode=1777
    privileged: true
    command: ["-d", "/etc/mihomo"]
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    restart: unless-stopped
    network_mode: host
    logging:
      driver: "json-file"
      options:
        max-size: "512m"
    healthcheck:
      test: ["CMD", "nc", "-z", "172.16.99.99", "9090"]
      interval: 60s
      timeout: 5s
      retries: 3
      start_period: 30s

  neko-master:
    image: foru17/neko-master
    container_name: neko
    restart: unless-stopped
    network_mode: host
    depends_on:
      - mihomo
    volumes:
      - ./data:/app/data
      - ./geoip:/app/data/geoip:ro
    environment:
      - NODE_ENV=production
      - DB_PATH=/app/data/stats.db
      - COOKIE_SECRET=b27989cdfe41d501af4d1b83e42d38e3efde1028274801391bafe08317ad955e # openssl rand -hex 32
      - TZ=Asia/Shanghai

  zashboard:
    depends_on:
      - mihomo
    container_name: zashboard
    image: ghcr.io/zephyruso/zashboard
    restart: unless-stopped
    dns:
      - 192.168.1.99
    ports:
      - "8080:80"
    environment:
      TZ: "Asia/Shanghai"
    logging:
      driver: "json-file"
      options:
        max-size: "128m"
